// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calculate_probabilities_helper
DataFrame calculate_probabilities_helper(DataFrame sortedInteractions, NumericVector isOutlier, bool useBinning, int desiredPerBin, double distScaling, int observedIntraInRangeSum);
RcppExport SEXP FitHiC_calculate_probabilities_helper(SEXP sortedInteractionsSEXP, SEXP isOutlierSEXP, SEXP useBinningSEXP, SEXP desiredPerBinSEXP, SEXP distScalingSEXP, SEXP observedIntraInRangeSumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type sortedInteractions(sortedInteractionsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type isOutlier(isOutlierSEXP);
    Rcpp::traits::input_parameter< bool >::type useBinning(useBinningSEXP);
    Rcpp::traits::input_parameter< int >::type desiredPerBin(desiredPerBinSEXP);
    Rcpp::traits::input_parameter< double >::type distScaling(distScalingSEXP);
    Rcpp::traits::input_parameter< int >::type observedIntraInRangeSum(observedIntraInRangeSumSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_probabilities_helper(sortedInteractions, isOutlier, useBinning, desiredPerBin, distScaling, observedIntraInRangeSum));
    return rcpp_result_gen;
END_RCPP
}
