// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calculate_probabilities_helper
DataFrame calculate_probabilities_helper(DataFrame sortedInteractions, NumericVector isOutlier, bool useBinning, int desiredPerBin, double distScaling, int observedIntraInRangeSum);
RcppExport SEXP FitHiC_calculate_probabilities_helper(SEXP sortedInteractionsSEXP, SEXP isOutlierSEXP, SEXP useBinningSEXP, SEXP desiredPerBinSEXP, SEXP distScalingSEXP, SEXP observedIntraInRangeSumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type sortedInteractions(sortedInteractionsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type isOutlier(isOutlierSEXP);
    Rcpp::traits::input_parameter< bool >::type useBinning(useBinningSEXP);
    Rcpp::traits::input_parameter< int >::type desiredPerBin(desiredPerBinSEXP);
    Rcpp::traits::input_parameter< double >::type distScaling(distScalingSEXP);
    Rcpp::traits::input_parameter< int >::type observedIntraInRangeSum(observedIntraInRangeSumSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_probabilities_helper(sortedInteractions, isOutlier, useBinning, desiredPerBin, distScaling, observedIntraInRangeSum));
    return rcpp_result_gen;
END_RCPP
}
// benjamini_hochberg_correction_helper
NumericVector benjamini_hochberg_correction_helper(NumericVector p_values, int num_total_tests, NumericVector sorted_pvals, IntegerVector order);
RcppExport SEXP FitHiC_benjamini_hochberg_correction_helper(SEXP p_valuesSEXP, SEXP num_total_testsSEXP, SEXP sorted_pvalsSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p_values(p_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type num_total_tests(num_total_testsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sorted_pvals(sorted_pvalsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(benjamini_hochberg_correction_helper(p_values, num_total_tests, sorted_pvals, order));
    return rcpp_result_gen;
END_RCPP
}
