# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_probabilities_helper <- function(sortedInteractions, isOutlier, useBinning, desiredPerBin, distScaling, observedIntraInRangeSum) {
    .Call('C_FitHiC_calculate_probabilities_helper', PACKAGE = 'FitHiC', sortedInteractions, isOutlier, useBinning, desiredPerBin, distScaling, observedIntraInRangeSum)
}

benjamini_hochberg_correction_helper <- function(p_values, num_total_tests, sorted_pvals, order) {
    .Call('C_FitHiC_benjamini_hochberg_correction_helper', PACKAGE = 'FitHiC', p_values, num_total_tests, sorted_pvals, order)
}

